testjob:
  only:
    - citest
    - master
    - module
  script:
    # set env
    - export PYTHONPATH="/home/wenqi/.local/lib/python2.7/site-packages":$PYTHONPATH
    - export PATH="/home/wenqi/.local/bin":$PATH
    - export CUDA_VISIBLE_DEVICES='1';

    # print system info
    - which nvidia-smi
    - nvidia-smi
    - pwd
    - python -c "import tensorflow as tf; print tf.__version__"
    - python -c "import tensorflow as tf; from tensorflow.python.client import device_lib; print device_lib.list_local_devices()"
    - ls -la /dev | grep nvidia

    # download data
    - wget -q https://www.dropbox.com/s/2unf08ylxvhc298/example_volumes.tar.gz
    - tar -xzvf example_volumes.tar.gz

    # run python code with coverage wrapper
    - coverage erase
    - coverage run -a --source . run_application.py train --image_size 42 --label_size 42 --batch_size 2
    - coverage run -a --source . run_application.py inference --image_size 64 --label_size 64 --batch_size 4
    - coverage run -a --source . -m testing.activation_test
    - coverage run -a --source . -m testing.bn_test
    - coverage run -a --source . -m testing.convolution_test
    - coverage run -a --source . -m testing.deconvolution_test
    - coverage run -a --source . -m testing.downsample_test
    - coverage run -a --source . -m testing.elementwise_test
    - coverage run -a --source . -m testing.highres3dnet_test
    - coverage run -a --source . -m testing.highresblock_test
    - coverage run -a --source . -m testing.upsample_test
    - coverage run -a --source . -m testing.toynet_test
    - coverage run -a --source . -m testing.crop_test
    - coverage run -a --source . -m testing.deepmedic_test
    - coverage run -a --source . -m testing.vnetblock_test
    - coverage run -a --source . -m testing.vnet_test
    - coverage run -a --source . -m testing.unetblock_test
    - coverage run -a --source . -m testing.unet_test
    - coverage run -a --source . -m testing.scaleblock_test
    - coverage run -a --source . -m testing.scalenet_test
    - coverage run -a --source . -m testing.input_queue_test
    - coverage report
    - echo 'finished test'
  tags:
    - gift-linux
